public class Constants { 
    
    public static final Integer API_TIMEOUT = 90000;  
   // public static final String GET_OAUTH_TOKEN = '/api/oauth2/token';
    public static final String GET_OAUTH_TOKEN_url = 'https://login.salesforce.com/services/oauth2/token';
    
    public static final String grant_type = 'password';  
    public static final String client_id = '3MVG9fe4g9fhX0E5KgAAkrCyF_fgktqR6VvaS4jU91Q8R7PzMkvH8VGqLzISKQ0ugVE7oy3DDxO.PZcunifZm';  
    public static final String client_secret = '39CEEC0D371661E5A8679C7F725A596B5EEDF4DFF7DA9256C74BE2515BB2F537';
    public static final String  username = 'mohanakrishnaintegration@salesforce.com';
    public static final String  password = 'Welcome123!z4xukaBS4AKUSzfBBtzyZmue'; 
    
    /*  public static final String OTP_CREATE_D2C_CUSTOMER = '/private/alliance/customer';  
	    public static final String OTP_GENERATE_OTP = '/api/salesforce/otp/generate';  
        public static final String OTP_VALIDATE_OTP = '/api/salesforce/otp/validate';  
        public static final String OTP_SEND_RECEIPT = '/api/salesforce/send/receipt'; */  
       
    
    
}